/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gym_management;
import static java.lang.String.format;

/**
 *
 * @author hp
 */
public class BMI_Calculator extends javax.swing.JFrame {
    public double weight = 0.0d, height = 0.0d, bmi =0.0d;

    /**
     * Creates new form BMI_Calculator
     */
    public BMI_Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        weightValue = new javax.swing.JTextField();
        heightValue = new javax.swing.JTextField();
        enter = new java.awt.Button();
        kg = new javax.swing.JRadioButton();
        lbs = new javax.swing.JRadioButton();
        inches = new javax.swing.JRadioButton();
        cm = new javax.swing.JRadioButton();
        output = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        clear = new java.awt.Button();
        button1 = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Weight");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 71, 50, -1));

        jLabel2.setText("Height");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 111, -1, -1));
        getContentPane().add(weightValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 68, 129, -1));
        getContentPane().add(heightValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 108, 127, -1));

        enter.setBackground(new java.awt.Color(255, 153, 0));
        enter.setForeground(new java.awt.Color(255, 255, 255));
        enter.setLabel("ENTER");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 150, -1, -1));

        buttonGroup1.add(kg);
        kg.setSelected(true);
        kg.setText("kg");
        getContentPane().add(kg, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 69, -1, -1));

        buttonGroup1.add(lbs);
        lbs.setText("lbs");
        lbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbsActionPerformed(evt);
            }
        });
        getContentPane().add(lbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 69, -1, -1));

        buttonGroup2.add(inches);
        inches.setSelected(true);
        inches.setText("inches");
        getContentPane().add(inches, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 109, -1, -1));

        buttonGroup2.add(cm);
        cm.setText("cm");
        getContentPane().add(cm, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 109, -1, -1));

        output.setText("BMI:");
        output.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 148, 196, 46));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel3.setFont(new java.awt.Font("Jokerman", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BODY MASS INDEX CALCULATOR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel3)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel5.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Wishing Your Good Health");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel5)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 266, -1, -1));

        clear.setBackground(new java.awt.Color(255, 0, 0));
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setLabel("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 161, -1, 25));

        button1.setBackground(new java.awt.Color(0, 0, 102));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("NEXT");
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 197, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gym_management/logo.jpeg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, -1, 218));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
         weight = Double.parseDouble(weightValue.getText());
         height = Double.parseDouble(heightValue.getText());
         
         
    if(lbs.isSelected()){
        weight = weight / 2.205;
}
     if(inches.isSelected()){
        height= height / 39.37;
}  
     else if(cm.isSelected()){
        height= height / 100;
} 
     bmi=weight/(height*height);
     System.out.println(bmi);
     if(bmi>=30){
         output.setText(format("%.2f obese", bmi));
     }
     else if(bmi>=25){
         output.setText(format("%.2f overweight" , bmi));
     }
     else if(bmi>=18.5){
         output.setText(format("%.2f normalweight" , bmi));
     }else{
         output.setText(format("%.2f underweight" , bmi));
     }
    }//GEN-LAST:event_enterActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
         weightValue.setText("");
         heightValue.setText("");
         output.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void lbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbsActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.Button clear;
    private javax.swing.JRadioButton cm;
    private java.awt.Button enter;
    private javax.swing.JTextField heightValue;
    private javax.swing.JRadioButton inches;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton kg;
    private javax.swing.JRadioButton lbs;
    private javax.swing.JLabel output;
    private javax.swing.JTextField weightValue;
    // End of variables declaration//GEN-END:variables
}
